
/* 

<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>




*/



#include <stdio.h>

int main()
{
   
   int num1 = 1, num2 = 2, num3, temp;
   
   
   
   long sum_even = 0;
   
   
   while(num1 < 4000000) {
       
       temp = num1 + num2;
       num1 = num2;
       num2 = num3;
       num3 = temp;
       
       if(num1 % 2 == 0) {
           
           sum_even += num1;
           
       }
       
       
       
       
   }
   
   
   printf("Sum = %ld", sum_even);
   
   
    return 0;
}
